### ISSUE TITLE
Probleem met laden van resources (css/js-bestanden)

### ISSUE THREAD

**Issue by vbrh-immalle** [WesleyVL-immalle/Gipwebsite#1]
Voorlopig lijkt er nog iets mis te zijn met je website i.v.m. het laden van css- en javascript-bestanden. Enig idee hoe dit komt?

Dit zie ik in de console: 
![image](https://user-images.githubusercontent.com/2732197/174132729-339b23e4-5b9a-48e5-9de5-3be0e0942ce6.png)

**Comment by WesleyVL-immalle** [comment]
opgelost in de commit laatste voorbereidingen.
